Front end/phase07 unit test
Star-Academy/codestar-internship pull request #106
Opened 2021-07-30 16:29 UTC by heidarzade-mh

2021-07-30 16:41 UTC, AlirezaT99 commented on Projects/Frontend/PhaseF07-UnitTest/PhaseF07-UnitTest.md
> +    ```
Change to "``` js" for code highlight

2021-07-30 21:22 UTC, BijanEisapour requested changes
<p dir='rtl' align='right'>
آقا خیلی عالیه خسته نباشی

2021-07-30 21:22 UTC, BijanEisapour commented on Projects/Frontend/PhaseF07-UnitTest/PhaseF07-UnitTest.md
> +# فاز هفتم: Unit Test
<p dir='rtl' align='right'>
فاز هفت به جای هفتم که با بقیۀ فازها جور در بیاد

2021-07-30 21:22 UTC, BijanEisapour commented on Projects/Frontend/PhaseF07-UnitTest/PhaseF07-UnitTest.md
> +[لیست تسک‌های مرتبط با این فاز به صورت issue template](./issue-template-PhaseF07.md)
<p dir='rtl' align='right'>
از این چیزا نداریم دیگه
<br>
واسه هر فاز issue template داریم یارو خیلی شیک میره از همونجا انتخاب میکنه واسش میاره همه چی رو

2021-07-30 21:22 UTC, BijanEisapour commented on Projects/Frontend/PhaseF07-UnitTest/issue-template-PhaseF07.md
> +  - Unit Testing Tools
<p dir='rtl' align='right'>
این چک باکسش جا افتاده

2021-07-30 21:22 UTC, BijanEisapour commented on Projects/Frontend/PhaseF07-UnitTest/PhaseF07-UnitTest.md
> +درباره `beforeEach` و `afterEach` مطالعه نمایید. میتوانید از مجموعه لینک زیر استفاده نمایید:
<p dir='rtl' align='right'>
یه سری جاها نیم‌فاصله نذاشتی. مثلا "می‌توانید"

2021-07-30 21:22 UTC, BijanEisapour commented on Projects/Frontend/PhaseF07-UnitTest/PhaseF07-UnitTest.md
> +حال که با مفاهیم تست‌نویسی و ابزارهای آن آشنا شده‌اید سعی کنید برای پروژه `spotify` تست‌نویسی کنید. همچنین سعی کنید تست‌های خود را با `code coverage` بالای ۹۰ درصد بنویسید.
<p dir='rtl' align='right'>
عبارات انگلیسی رو Title Case بنویس

2021-07-30 21:22 UTC, BijanEisapour commented on Projects/Frontend/PhaseF07-UnitTest/PhaseF07-UnitTest.md
> +## بخش اول: مفاهیم تست‌نویسی و اهمیت آن
<p dir='rtl' align='right'>
تو داک‌های فرانت بخش‌بندی نداریم
<br>
به جاش تعداد هشتگ‌ها به این شکله که واسه تیتر اول یه دونه، واسه "مقدمه"، "نصب"، "یادگیری" و "پروژه" دوتا و واسه هر چیزی که داخل اینا باشه سه و چهارتا استفاده میشه

2021-07-31 18:59 UTC, BijanEisapour approved these changes

2021-07-31 19:00 UTC, merged