Phase11 advanced components
Star-Academy/codestar-internship pull request #111
Opened 2021-08-06 16:20 UTC by heidarzade-mh

2021-08-09 11:17 UTC, BijanEisapour requested changes

2021-08-09 11:17 UTC, BijanEisapour commented on Projects/Frontend/PhaseF11-Advanced-Components/PhaseF11-AdvancedComponents.md
> +<div dir="rtl" align='justify'>
<div dir='rtl' align='right'>
فایل‌های جانبی مثل عکس و اوگما داخل پوشۀ جداگانه قرار بگیرن مثلاً Images و Scripts

2021-08-09 11:17 UTC, BijanEisapour commented on Projects/Frontend/PhaseF11-Advanced-Components/PhaseF11-AdvancedComponents.md
> +# فاز یازده: Addvanced Components
<div dir='rtl' align='right'>
اشتباه تایپی

2021-08-09 11:17 UTC, BijanEisapour commented on Projects/Frontend/PhaseF11-Advanced-Components/PhaseF11-AdvancedComponents.md
> +در این فاز شما با سه کامپوننت پیشرفته آشنا می‌شوید که کمک زیادی در نمایش داده‌خام میکند. نمایش داده‌ها و توانایی خوانایی آن توسط انسان، کمک زیادی به تحلیل و دسته‌بندی داده‌ها میکند. اصولا داده‌های خا
<div dir='rtl' align='right'>
داده‌خام نباید سرهم باشه

2021-08-09 11:17 UTC, BijanEisapour commented on Projects/Frontend/PhaseF11-Advanced-Components/PhaseF11-AdvancedComponents.md
> +همانطور که پیشتر اشاره کردیم مصورسازی اطلاعات کمک زیادی در روند تحلیل داده‌خام میکند. یکی از روش‌های مصورسازی اطلاعات، گراف است. اصولا داده‌هایی که الگوی ارتباطی دارند را بر روی گراف نمایش می‌دهند. ی
<div dir='rtl' align='right'>
تنوین اصولاً

2021-08-09 11:17 UTC, BijanEisapour commented on Projects/Frontend/PhaseF11-Advanced-Components/PhaseF11-AdvancedComponents.md
> +<p align="center" style="width:70% text-align:center;" ><img src="datawalk.png" alt="Logo"  align="cneter"  style="center"></p>
alt="Logo" ?!

<div dir='rtl' align='right'>
بعد به نظرم نیازی نیست عکس رو داخل p بذاری، خود img کافیه

2021-08-09 11:17 UTC, BijanEisapour commented on Projects/Frontend/PhaseF11-Advanced-Components/PhaseF11-AdvancedComponents.md
> +نوع خاصی از داده وجود دارد که برای مصورسازی آنها میبایست از نقشه‌ها کمک بگیریم. برای مثال برای مدریت راه‌ها در کشور، لازم است داده‌های جمع‌آوری شده، بر روی نقشه مصورسازی شود. شما در نظر بگیرید مسئول
<div dir='rtl' align='right'>
برای مثال برای "مدیریت" راه‌ها در کشور

2021-08-09 11:17 UTC, BijanEisapour commented on Projects/Frontend/PhaseF11-Advanced-Components/PhaseF11-AdvancedComponents.md
> +در ابتدا `OGMA` را داخل `Angular` امتحان کنید و برای پیاده‌سازی آن به [providing-ogma](providing-ogma.md) مراجعه کنید.
<div dir='rtl' align='right'>
به نظرم OGMA رو داخل `` نذار چون بالاتر این کارو نکردی، واسه mapbox gl هم همینطور

2021-08-09 11:17 UTC, BijanEisapour commented on Projects/Frontend/PhaseF11-Advanced-Components/PhaseF11-AdvancedComponents.md
> +```
<div dir='rtl' align='right'>
نوع کد رو بذار bash

2021-08-09 11:17 UTC, BijanEisapour commented on Projects/Frontend/PhaseF11-Advanced-Components/PhaseF11-AdvancedComponents.md
> +```
<div dir='rtl' align='right'>
نوع کد رو بذار bash

2021-08-09 11:17 UTC, BijanEisapour commented on Projects/Frontend/PhaseF11-Advanced-Components/PhaseF11-AdvancedComponents.md
> +هر سه کامپوننت معرفی شده دارای داکیومنتی بسیار قوی هستند که ۹۹ درصد نیازهای شما را پوشش میدهد و به راحتی میتوانید نیازمندی خود را در آنها بیابید..
<div dir='rtl' align='right'>
تهش دو تا نقطه گذاشتی

2021-08-09 11:17 UTC, BijanEisapour commented on Projects/Frontend/PhaseF11-Advanced-Components/providing-ogma.md
> +</div>
<div dir='rtl' align='right'>
به نظرم این فایل به کل حذف شه چون به اندازۀ کافی لینک واسه راه‌اندازی پروژه معرفی کردی

2021-08-09 11:17 UTC, BijanEisapour commented on Projects/Frontend/PhaseF11-Advanced-Components/issue-template-PhaseF11.md
> +  - [ ] Visualize fake data
Visualize Fake Data

2021-08-15 16:57 UTC, heidarzade-mh commented on Projects/Frontend/PhaseF11-Advanced-Components/providing-ogma.md
> +</div>
وجودش لازمه. منتقل شد به فایل اصلی که دو تا داکیومنت نباشه

2021-08-15 18:21 UTC, BijanEisapour approved these changes

2021-08-15 18:22 UTC, merged