Phase 20, python, Colab, dataframe & Iran Covid 19 ETL
Star-Academy/codestar-internship pull request #113
Opened 2021-08-18 13:05 UTC by mhaghighat20

Closes #91

2021-08-19 16:53 UTC, Parsa2820 reviewed
کلمات انگلیسی بعضی جاها حرف اولش بزرگ بود، بعضی جاها نبود که بهتره یکدست بشه

تا سر پروژه بررسی کردم. خیلی خوب بود. خسته نباشید 👍

2021-08-20 04:25 UTC, mhaghighat20 commented on Projects/Phase20-Colab/Phase20-Colab.md
> +با استفاده از Dataframe در کتابخانه pandas می توان می توان انواع عملیات ETL و Visualize داده را انجام داد. در این قسمت می‌خواهیم با استفاده از فایل‌های csv دیتاست های معروف دو تمرین دستگرمی انجام دهی
done

2021-08-20 04:25 UTC, mhaghighat20 commented on Projects/Phase20-Colab/Phase20-Colab.md
> +برای این که بهتر متوجه شوید لینک زیر را باز کنید و با Colab کار کنید:
done

2021-08-20 04:26 UTC, mhaghighat20 commented on Projects/Phase20-Colab/Phase20-Colab.md
> +محصول Google Colaboratory یا Colab یک ابزار بسیار راحت برای کار با داده ها به زبان python است. با استفاده از Colab می‌توانید کد های python را در مرورگر خود بنویسید و اجرای آن‌ها را به سرور بسپارید و
done

2021-08-20 04:32 UTC, mhaghighat20 commented on Projects/Phase20-Colab/Phase20-Colab.md
> + * [Python Dict and File](https://developers.google.com/edu/python/dict-files)
بیشتر بررسی کردم و متوجه شدم کار با 
string
کاربرد زیادی در ادامه مسیر نداره و بیشتر مواردش مربوط به 
python 2
هست بنابراین حذفش کردم
از طرف دیگه موقع نوشتن گشتم دنبال آموزش 
python3
ولی چیزی مطلبی بهتر از آموزش های گوگل پیدا نکردم

2021-08-20 04:34 UTC, mhaghighat20 commented on Projects/Phase20-Colab/Phase20-Colab.md
> +با استفاده از Dataframe در کتابخانه pandas می توان می توان انواع عملیات ETL و Visualize داده را انجام داد. در این قسمت می‌خواهیم با استفاده از فایل‌های csv دیتاست های معروف دو تمرین دستگرمی انجام دهی
fixed

2021-08-20 04:35 UTC, mhaghighat20 commented on Projects/Phase20-Colab/Phase20-Colab.md
> +محصول Google Colaboratory یا Colab یک ابزار بسیار راحت برای کار با داده ها به زبان python است. با استفاده از Colab می‌توانید کد های python را در مرورگر خود بنویسید و اجرای آن‌ها را به سرور بسپارید و
fixed

2021-08-20 04:36 UTC, mhaghighat20 commented on Projects/Phase20-Colab/Phase20-Colab.md
> + برای این کار آشنایی مقدماتی با python لازم است. اگر با python آشنایی ندارید می‌توانید با مطالعه لینک‌های برای ادامه کار آماده شوید:
fixed

2021-08-20 08:41 UTC, mostmand requested changes
دمت گرم خیلی عالی بود یه سری کامنت درباره‌ی نکات نگارشی گذاشته شد

2021-08-20 08:41 UTC, mostmand commented on Projects/Phase20-Colab/Phase20-Colab.md
> +*  ساده و نزدیک به زبان انسان هست و برای بسیاری از Data Scientist ها که ممکن است تجربه‌ی کار با زبان‌های اصلی Object Oriented  و مفاهیم پیشرفته دنیای مهندسی نرم افزار را نداشته باشند، یادگیری راحتی د
bulletهایی
که به عنوان مزایای پایتون آمده‌اند بهتر است همه به یک صورت باشند یا همه به صورت جمله باشند یا همه‌ی آن‌ها مصدری باشند مثلاً این طوری:
احتمالاً بارها اسم این زبان را شنیده‌اید. این زبان محبوبیت زیادی بین
Data Scientistها
دارد. از دلایل آن این می‌توان به موارد زیر اشاره کرد:
* نزدیکی به زبان انسان
* یادگیری راحت برای افرادی که تجربه‌ی کار با زبان‌های Object Oriented نداشته‌اند
* وجود کتاب‌خانه‌های زیاد و متنوع به زبان پایتون در حوزه‌ی Data Science

2021-08-20 08:41 UTC, mostmand commented on Projects/Phase20-Colab/Phase20-Colab.md
> +محصول Google Colaboratory یا Colab یک ابزار بسیار راحت برای کار با داده‌ها به زبان python است. با استفاده از Colab می‌توانید کد‌های python را در مرورگر خود بنویسید و اجرای آن‌ها را به سرور بسپارید و
انتهای این پاراگراف این طوری خواناتره به نظرم:
و بدون این که رایانه‌ی خودتان درگیر اجرای کد شود، نتیجه‌ی اجرا را در مرورگر خود مشاهده کنید.

2021-08-20 08:41 UTC, mostmand commented on Projects/Phase20-Colab/Phase20-Colab.md
> +آشنایی مقدماتی با Colab به پایان رسید، برای جزئیات بیشتر و رفع ابهام می‌توانید به لینک زیر مراجعه کنید:
این جمله بهتره این طوری باشه:
پس از آشنایی مقدماتی با
Colab
برای جزئیات بیش‌تر و رفع ابهام می‌توانید به لینک زیر مراجعه کنید:

2021-08-20 08:41 UTC, mostmand commented on Projects/Phase20-Colab/Phase20-Colab.md
> +با استفاده از DataFrame در کتابخانه pandas می‌توان انواع عملیات ETL و Visualize داده را انجام داد. در این قسمت می‌خواهیم با استفاده از فایل‌های csv دیتاست های معروف دو تمرین دستگرمی انجام دهیم:
بعد از معروف یک کاما به نظرم جمله رو خواناتر می‌کنه

2021-08-20 08:41 UTC, mostmand commented on Projects/Phase20-Colab/Phase20-Colab.md
> +## پروژه اصلی - تحلیل داده‌های شیوع کرونا در ایران
کلمه‌ی اصلی به نظرم اضافه است و می‌تونه حذف بشه

2021-08-20 08:41 UTC, mostmand commented on Projects/Phase20-Colab/Phase20-Colab.md
> +برای راحتی بیشتر شما در انجام این پروژه یک notebook آماده و تحلیل‌ها و خروجی‌های مورد نظر در آن نشان داده شده‌است. سپس بخش‌هایی از کد را پاک کردیم تا شما پیاده‌سازی کنید. لینک زیر را باز کنید و سپس م
کلمه‌ی محتویات به اشتباه محتوایات نوشته شده

2021-08-20 08:41 UTC, mostmand commented on Projects/Phase20-Colab/Phase20-Colab.md
> +در پایان پروژه، notebook ویرایش شده‌ی خودتان را با استفاده از دگمه Share در گوشه‌ی بالا سمت راست صفحه‌ی Colab با دیگران به اشتراک بگذارید و دسترسی Comment گذاری به آن‌ها بدهید و لینک تولید شده را در
کلمه‌ی دکمه به اشتباه دگمه نوشته شده است

2021-08-20 08:41 UTC, mostmand commented on Projects/Phase20-Colab/Phase20-Colab.md
> +* [Iran-Covid-ETL-notebook.ipynb](https://colab.research.google.com/github/Star-Academy/codestar-internship/blob/feature%2FSE-phase20/Projects/Phase20-Colab/Iran-Covid-ETL-notebook.ipynb)
بهتر نیست لینک ریپوی خودمون رو بذاریم و اون جا بچه‌ها دکمه‌ی
Open in Colab
رو خودشون بزنن؟ به این علت میگم که این لینک به طور مطلق نوشته شده و وقتی برنچ
feature/SE-phase20
پاک بشه و بره روی مستر دیگه معتبر نیست. به نظرم بهتره لینک نسبی توی ریپوی خودمون داده بشه

2021-08-20 08:41 UTC, mostmand commented on Projects/Phase20-Colab/Phase20-Colab.md
> +<div dir="rtl" align='justify'>
کامنت‌هایی که روی نوت بوک
Iran-Covid-ETL-notebook.ipynb
دارم رو اینجا می‌ذارم چون گیت‌هاب درست نوت بوک رو توی پول ریکوئست نشون نمیده
در عنوان
Join "vaccination data" with "case & death data"
بهتر است کلمه‌ی
with
با کلمه‌ی
and
جایگزین شود

در همین بخش جمله‌ی
We want to join two dataframes
بهتر است این گونه باشد:
Join two dataframes ...

در بخش
Calculate sum/avg/max/min MONTHLY Aggregation
جمله‌ی اول بهتر است به طور مجهول نوشته شود:
Aggregation is used to summarize data for better analysis and understanding. Aggregations have main role in generating reports & charts.

2021-08-20 09:11 UTC, mhaghighat20 commented on Projects/Phase20-Colab/Phase20-Colab.md
> +*  ساده و نزدیک به زبان انسان هست و برای بسیاری از Data Scientist ها که ممکن است تجربه‌ی کار با زبان‌های اصلی Object Oriented  و مفاهیم پیشرفته دنیای مهندسی نرم افزار را نداشته باشند، یادگیری راحتی د
fixed

2021-08-20 09:12 UTC, mhaghighat20 commented on Projects/Phase20-Colab/Phase20-Colab.md
> +آشنایی مقدماتی با Colab به پایان رسید، برای جزئیات بیشتر و رفع ابهام می‌توانید به لینک زیر مراجعه کنید:
fixed

2021-08-20 09:13 UTC, mhaghighat20 commented on Projects/Phase20-Colab/Phase20-Colab.md
> +## پروژه اصلی - تحلیل داده‌های شیوع کرونا در ایران
fixed

2021-08-20 09:13 UTC, mhaghighat20 commented on Projects/Phase20-Colab/Phase20-Colab.md
> +در پایان پروژه، notebook ویرایش شده‌ی خودتان را با استفاده از دگمه Share در گوشه‌ی بالا سمت راست صفحه‌ی Colab با دیگران به اشتراک بگذارید و دسترسی Comment گذاری به آن‌ها بدهید و لینک تولید شده را در
fixed

2021-08-20 09:18 UTC, mhaghighat20 commented on Projects/Phase20-Colab/Phase20-Colab.md
> +<div dir="rtl" align='justify'>
fixed

2021-08-20 09:20 UTC, mhaghighat20 commented on Projects/Phase20-Colab/Phase20-Colab.md
> +برای راحتی بیشتر شما در انجام این پروژه یک notebook آماده و تحلیل‌ها و خروجی‌های مورد نظر در آن نشان داده شده‌است. سپس بخش‌هایی از کد را پاک کردیم تا شما پیاده‌سازی کنید. لینک زیر را باز کنید و سپس م
fixed

2021-08-20 09:21 UTC, mhaghighat20 commented on Projects/Phase20-Colab/Phase20-Colab.md
> +با استفاده از DataFrame در کتابخانه pandas می‌توان انواع عملیات ETL و Visualize داده را انجام داد. در این قسمت می‌خواهیم با استفاده از فایل‌های csv دیتاست های معروف دو تمرین دستگرمی انجام دهیم:
fixed

2021-08-20 09:22 UTC, mhaghighat20 commented on Projects/Phase20-Colab/Phase20-Colab.md
> +محصول Google Colaboratory یا Colab یک ابزار بسیار راحت برای کار با داده‌ها به زبان python است. با استفاده از Colab می‌توانید کد‌های python را در مرورگر خود بنویسید و اجرای آن‌ها را به سرور بسپارید و
fixed

2021-08-20 09:25 UTC, mhaghighat20 commented on Projects/Phase20-Colab/Phase20-Colab.md
> +* [Iran-Covid-ETL-notebook.ipynb](https://colab.research.google.com/github/Star-Academy/codestar-internship/blob/feature%2FSE-phase20/Projects/Phase20-Colab/Iran-Covid-ETL-notebook.ipynb)
به این قضیه فکر کردم اما ظاهرا 
badge
مربوط به
open in colab
هم به صورت نسبی کار نمی کنه

2021-08-20 09:26 UTC, mhaghighat20 commented on Projects/Phase20-Colab/Phase20-Colab.md
> +* [Iran-Covid-ETL-notebook.ipynb](https://colab.research.google.com/github/Star-Academy/codestar-internship/blob/feature%2FSE-phase20/Projects/Phase20-Colab/Iran-Covid-ETL-notebook.ipynb)
بعد از نهایی شدن 
PR
لینک رو اصلاح می کنم

2021-08-20 12:36 UTC, mostmand approved these changes

2021-08-21 04:58 UTC, alrz1999 reviewed
خیلی عالی بود. خسته نباشید.

2021-08-22 13:44 UTC, mhaghighat20 commented on Projects/Phase20-Colab/Phase20-Colab.md
> +*  برای بسیاری از Data Scientist ها که ممکن است تجربه‌ی کار با زبان‌های اصلی Object Oriented  و مفاهیم پیشرفته دنیای مهندسی نرم افزار را نداشته باشند، یادگیری راحتی دارد.
fixed

2021-08-25 08:23 UTC, Parsa2820 commented on Projects/Phase20-Colab/Iran-Covid-ETL-notebook.ipynb
> +        "First of all we collect data from from this open source repository, which hosts latest stats from covid 19 about many countries:\r\n",
... latest stats for Covid-19 in many countries:

2021-08-25 08:23 UTC, Parsa2820 commented on Projects/Phase20-Colab/Iran-Covid-ETL-notebook.ipynb
> +            "image/png": "iVBORw0KGgoAAAANSUhEUgAACYUAAAQoCAYAAABfWiOaAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAewgAAHsIBbtB1PgAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjIsIGh0dHA6Ly9tYXRwbG90bGliL
<p dir="rtl">
فاز 7 با جوین sql آشنا شدن. میتونیم لینک همونو بذاریم و بگیم قبلا باهاش آشنا شدید
</p>

2021-10-03 09:44 UTC, merged