اصلاح و بانویسی مستندات برای کداستار 1401
Star-Academy/codestar-internship pull request #117
Opened 2022-06-09 14:42 UTC by RAAvenger

2022-06-13 14:55 UTC, BijanEisapour requested changes

2022-06-13 14:55 UTC, BijanEisapour commented on Technical/Software Engineering/Simple Project/Readme.md
> +در این بخش یک موتور جستجوی ساده می‌نویسیم که متن حجیمی را به عنوان ورودی بگیرد، پردازش‌های لازم را روی آن انجام دهد تا در نهایت کاربر بتواند روی متن‌هایی که قبلا وارد شده بود، جستجو کند.
به‌عنوان

2022-06-13 14:55 UTC, BijanEisapour commented on Technical/Software Engineering/Simple Project/Readme.md
> +- چطور می‌شود این جستجو را از مرتبه‌ی یک یا همان  (O(1 یک انجام داد؟
‫"(O(1 یک" حشو داره

2022-06-13 14:55 UTC, BijanEisapour commented on Technical/Software Engineering/Simple Project/Readme.md
> +یکی از داده ساختارهایی که برای پیاده سازی موتور جستجو قابل استفاده است، Inverted Index می‌باشد. برای آشنایی با این داده ساختار [Inverted Index - GeeksforGeeks](https://www.geeksforgeeks.org/inverted-
داده‌ساختار
پیاده‌سازی
قابل‌استفاده

2022-06-13 14:55 UTC, BijanEisapour commented on Technical/Software Engineering/Simple Project/Readme.md
> +ویدئوی [The Inverted Index Stanford NLP](https://www.youtube.com/watch?v=bnP6TsqyF30) را مشاهده نمایید.
The Inverted Index
ادامه‌ش اومده اسم کامل استاد رو نوشته، که اهمیتی نداره

2022-06-13 14:55 UTC, BijanEisapour commented on Technical/Software Engineering/Simple Project/Readme.md
> +برنامه‌ای به **زبان جاوا** بنویسید که تعدادی داکیومنت را بخواند و از روی آن‌ها یک  Inverted Index بسازد.
Java
‫نیازی هم به boldکردن نیست
Document

2022-06-13 14:55 UTC, BijanEisapour commented on Technical/Software Engineering/Simple Project/Readme.md
> +ویدئوی [The Inverted Index Stanford NLP](https://www.youtube.com/watch?v=bnP6TsqyF30) را مشاهده نمایید.
The Inverted Index
ادامه‌ش اومده اسم کامل استاد رو نوشته، که اهمیتی نداره

2022-06-13 14:55 UTC, BijanEisapour commented on Technical/Software Engineering/Simple Project/Readme.md
> +برنامه‌ای به **زبان جاوا** بنویسید که تعدادی داکیومنت را بخواند و از روی آن‌ها یک  Inverted Index بسازد.
تهش باید نقطه‌ویرگول بذاری چون به جملۀ بعدی متصله

2022-06-13 14:55 UTC, BijanEisapour commented on Technical/Software Engineering/Simple Project/Readme.md
> +سپس از کاربر یک کلمه ورودی بگیرد و نام داکیومنت‌هایی که شامل آن کلمه هستند را چاپ کند.
‫سپس در Console از کاربر یک ورودی به عنوان کلمه بگیرد و نام Documentهایی را که شامل آن کلمه هستند، چاپ کند.

2022-06-13 14:55 UTC, BijanEisapour commented on Technical/Software Engineering/Simple Project/Readme.md
> +- پیشنهاد می‌کنیم از دیتاست  [The 20 Newsgroups data set](./SampleEnglishData.zip) برای تست برنامه استفاده کنید.
‫کلمۀ "دیتاست" حذف بشه

The 20 Newsgroups Dataset

‫اسم فایل zip هم اصلاح بشه و دقیقاً به همین تغییر کنه

2022-06-13 14:55 UTC, BijanEisapour commented on Technical/Software Engineering/Simple Project/Readme.md
> +- برای بالا بردن دقت جستجو تمام داکیومنت‌های ورودی را Uppercase کنید.
من که کلاً نفهمیدم این جمله یعنی چی
چی رو باید Uppercase کنن؟ اسم فایل‌ها رو؟
بعد این جه ربطی به دقت جستجو داره؟

2022-06-13 14:55 UTC, BijanEisapour commented on Technical/Software Engineering/Simple Project/Readme.md
> +   1. کلماتی که نمی‌بایست در نتیجه وجود داشته باشند، با پیشوند '-' مشخص می‌شوند.
به جای ' از کاراکتر ` برای اینجور جاها استفاده کن که فرمت Code به اون عبارت بدی

2022-06-13 14:55 UTC, BijanEisapour commented on Technical/Software Engineering/Simple Project/Readme.md
> +*ورودی نوع اول مانند And، نوع دوم مانند Or و نوع سوم مانند Not می‌باشد.*
به نظرم اضافیه 
خودشون میفهمن 
پاک بشه

2022-06-13 14:55 UTC, BijanEisapour commented on Technical/Software Engineering/Simple Project/Readme.md
> +### مثال:
دونقطه تو تیترها نداریم

2022-06-13 14:55 UTC, BijanEisapour commented on Technical/Software Engineering/Simple Project/Readme.md
> +` get help +illness +disease -cough `
یه جوری به بازی ربطش بده 
مثلاً یه آیتمی رو میخوای تو Dota 2 سرچ کنی یا خواص یه سلاحی تو Elden Ring

2022-06-13 14:55 UTC, BijanEisapour commented on Technical/Software Engineering/Simple Project/Readme.md
> +کوئری بالا به معنای داکیومنت‌هایی است که حتماً get و help را داشته باشند، شامل حداقل یکی از کلمات illness یا disease باشند و cough را نداشته باشند.
با استفاده از Query بالا می‌توانیم Documentهایی را پیدا کنیم که حتماً شامل عبارات `get` و `help` و همچنین حداقل یکی از عبارات `illness` و `disease` باشند و شامل عبارت `cough` نباشند.

2022-06-13 14:55 UTC, BijanEisapour commented on Technical/Software Engineering/Simple Project/Readme.md
> + برای آشنایی بیشتر با نحوه‌ی کار موتور‌های جستجو دیدن ویدئوی [How Google searches one document among Billions of documents quickly](https://www.youtube.com/watch?v=CeGtqouT8eA) توصیه می‌شود.
کلماتی که به `ی` ختم میشن رو با `ۀ` بنویس 
مثلاً نحوه‌ی => نحوۀ
Shift + G

2022-06-13 14:55 UTC, BijanEisapour commented on Technical/Software Engineering/Simple Project/Readme.md
> + برای آشنایی بیشتر با نحوه‌ی کار موتور‌های جستجو دیدن ویدئوی [How Google searches one document among Billions of documents quickly](https://www.youtube.com/watch?v=CeGtqouT8eA) توصیه می‌شود.
برای آشنایی بیشتر با نحوۀ کار موتور‌های جستجو، پیشنهاد می‌کنیم [How Google searches one document among Billions of documents quickly](https://www.youtube.com/watch?v=CeGtqouT8eA) را ببینید.

2022-06-13 14:55 UTC, BijanEisapour commented on Technical/Software Engineering/Simple Project/Readme.md
> +- پیشنهاد می‌کنیم از دیتاست  [The 20 Newsgroups data set](./SampleEnglishData.zip) برای تست برنامه استفاده کنید.
اگه بتونی یه دیتاست پیدا کنی که مربوط به بازی باشه خیلی خوب میشه 
مثلاً احتمالاً دیتاست استیم وجود داشته باشه 
یا مثلاً بیوگرافی کاراکترهای یه بازی مثه Rainbow
یا حتی داستان Elden Ring

2022-06-13 14:55 UTC, BijanEisapour commented on Technical/Software Engineering/Simple Project/issue-template-simpleProject.md
> +This issue template is based on [Phase01-Search.md](./Phase01-Search.md) contents. Go to [Issue Repo](https://github.com/Star-Academy/codestar-intern-issues/issues/new/choose) and click on Get starte
من این فایل رو کاری ندارم چون به نظرم تا وقتی ساختار مشترک بینِ داک‌ها وجود نداره، نمیشه خیلی روش دقیق شد و نظر داد 
در آینده یادمون باشه بهش برگردیم

2022-06-21 12:50 UTC, heidarzade-mh commented on Technical/Software Engineering/Simple Project/Readme.md
> +- پیشنهاد می‌کنیم از دیتاست  [The 20 Newsgroups data set](./SampleEnglishData.zip) برای تست برنامه استفاده کنید.
این دیتاست مربوط به سرچ است و کلی ملاحظات دارد
مثلا یک کلمه در چند داکیومنت باشد که موقع سرچ چند داکیومنت مشاهده شود.

2022-06-21 12:54 UTC, heidarzade-mh commented on Technical/Software Engineering/Simple Project/Readme.md
> +- برای بالا بردن دقت جستجو تمام داکیومنت‌های ورودی را Uppercase کنید.
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1308?view=vs-2022

2022-06-21 12:56 UTC, heidarzade-mh commented on Technical/Software Engineering/Simple Project/Readme.md
> +*ورودی نوع اول مانند And، نوع دوم مانند Or و نوع سوم مانند Not می‌باشد.*
باشه بهتره
سخت فهم میشه

2022-06-21 12:57 UTC, heidarzade-mh commented on Technical/Software Engineering/Simple Project/Readme.md
> +` get help +illness +disease -cough `
چون داکیومنت قرار نیست هر سال عوض بشه و ممکنه تم هر سال متفاوت باشه نظر بر این شد در داکیومنت ها تیم بازی آورده نشود.

2022-06-29 05:36 UTC, BijanEisapour commented on Technical/Software Engineering/Simple Project/Readme.md
> +برنامه‌ای به **زبان جاوا** بنویسید که تعدادی داکیومنت را بخواند و از روی آن‌ها یک  Inverted Index بسازد.
Java with Capital J

2022-06-29 05:44 UTC, BijanEisapour commented on Technical/Software Engineering/Simple Project/Readme.md
> +سپس در Console از کاربر یک ورودی به عنوان کلمه بگیرد و نام Document هایی را که شامل آن کلمه هستند، چاپ کند.
"هایی" باید بچسبه به کلمۀ قبلیش

2022-06-29 05:44 UTC, BijanEisapour commented on Technical/Software Engineering/Simple Project/Readme.md
> +- پیشنهاد می‌کنیم از دیتاست  [The 20 Newsgroups data set](./SampleEnglishData.zip) برای تست برنامه استفاده کنید.
قانع نشدم 
به نظرم ملاحظات زیادی نداره که نشه جای دیگه پیداش کرد 

فعلاً علی‌الحساب اسمش رو درست کنید ...
The 20 Newsgroups Dataset 
بعد در مورد دیتاست بهتر حرف بزنیم

2022-06-29 05:44 UTC, BijanEisapour commented on Technical/Software Engineering/Simple Project/Readme.md
> +- برای بالا بردن دقت جستجو تمام Document ‌های ورودی را Uppercase کنید.
بچسبون

2022-06-29 05:44 UTC, BijanEisapour commented on Technical/Software Engineering/Simple Project/Readme.md
> +   1. کلماتی که حداقل یکی از آن‌ها می‌بایست در نتیجه وجود داشته باشند، با پیشوند `+` مشخص می‌شوند.
می‌بایست => باید

2022-06-29 05:44 UTC, BijanEisapour commented on Technical/Software Engineering/Simple Project/Readme.md
> +   1. کلماتی که نمی‌بایست در نتیجه وجود داشته باشند، با پیشوند `-` مشخص می‌شوند.
نمی‌بایست => نباید

2022-06-29 05:44 UTC, BijanEisapour commented on Technical/Software Engineering/Simple Project/Readme.md
> +با استفاده از Query بالا می‌توانیم Document هایی را پیدا کنیم که حتماً شامل عبارات `get` و `help` و همچنین حداقل یکی از عبارات `illness` و `disease` باشند و شامل عبارت `cough` نباشند.
بچسبون

2022-06-29 05:44 UTC, BijanEisapour commented on Technical/Software Engineering/Simple Project/Readme.md
> +- برای بالا بردن دقت جستجو تمام داکیومنت‌های ورودی را Uppercase کنید.
چیه این اصن؟ چه ربطی به جستجو داره؟
حتی اگه ربط داشته باشه که به نظر من نداره، باید دقیق و واضح تو داک توضیح بدید چرا باید چنین کاری انجام بدن

2022-06-29 05:44 UTC, BijanEisapour commented on Technical/Software Engineering/Simple Project/Readme.md
> +` get help +illness +disease -cough `
چنین چیزی با من هماهنگ نشده 
صحبت کنیم

2022-06-29 05:44 UTC, BijanEisapour commented on Technical/Software Engineering/Simple Project/Readme.md
> + برای آشنایی بیشتر با نحوه‌ی کار موتور‌های جستجو دیدن ویدئوی [How Google searches one document among Billions of documents quickly](https://www.youtube.com/watch?v=CeGtqouT8eA) توصیه می‌شود.
کامنت دوم انجام نشده

2022-07-11 10:59 UTC, closed without merging