Add configuration section to learning resources
Star-Academy/codestar-internship pull request #53
Opened 2020-09-01 08:07 UTC by Parsa2820

2020-09-01 09:35 UTC, mahdimalverdi requested changes

2020-09-01 09:35 UTC, mahdimalverdi commented on Projects/Phase09-Web/Phase09-Web.md
> +در `Asp.net Core` تنظیمات برنامه میتواند از منابع مختلفی بیاید. یکی از پرکاربرد ترین آن ها فایل است. تغییر تنظیمات ذخیره شده در فایل نیاز به `Build` مجدد ندارد. از این رو استفاده از آن متداول است. با
نیم فاصله رو رعایت کن

2020-09-01 09:42 UTC, Parsa2820 commented on Projects/Phase09-Web/Phase09-Web.md
> +در `Asp.net Core` تنظیمات برنامه میتواند از منابع مختلفی بیاید. یکی از پرکاربرد ترین آن ها فایل است. تغییر تنظیمات ذخیره شده در فایل نیاز به `Build` مجدد ندارد. از این رو استفاده از آن متداول است. با
اصلاح شد

2020-09-05 04:02 UTC, mhaghighat20 approved these changes
عالی! این فرهنگ کانتریبیوت کردن و کمک کرد به بهبود داک ها خیلی خوبه، ایول پارسا جان

2020-09-05 12:31 UTC, merged