Phase 12
Star-Academy/codestar-internship pull request #59
Opened 2020-09-15 13:39 UTC by alrz1999

Closes #31

2020-09-16 16:37 UTC, mhaghighat20 requested changes
علیرضا دمت گرم خوب بود،‌ صرفا چند تا اصلاح ریز نوشتم که اگه اونا رو انجام بدی عالی میشه

2020-09-16 16:37 UTC, mhaghighat20 commented on Projects/Phase12-Apm/Phase12-Apm.md
> +    Performance Manitoring
fix typo! :)

2020-09-16 16:37 UTC, mhaghighat20 commented on Projects/Phase12-Apm/Phase12-Apm.md
> +    Elastic
<div dir='rtl'>
واژه شرکت اضافه بشه شاید بهتر باشه یعنی بنویسیم «محصول شرکت Elastic»
</div>

2020-09-16 16:37 UTC, mhaghighat20 commented on Projects/Phase12-Apm/Phase12-Apm.md
> +        ها لایبرری های
پیشنهاد می کنم همه استفاده ها از کلمه لایبرری رو با کتابخانه جایگزین کنی :)

2020-09-16 16:37 UTC, mhaghighat20 commented on Projects/Phase12-Apm/Phase12-Apm.md
> +        این بخش وظیفه‍ی دریافت اطلاعات از
وظیفه‍ی رو فاصله بذار :)

2020-09-17 04:46 UTC, alrz1999 commented on Projects/Phase12-Apm/Phase12-Apm.md
> +    Performance Manitoring
fixed

2020-09-17 04:46 UTC, alrz1999 commented on Projects/Phase12-Apm/Phase12-Apm.md
> +    Elastic
fixed

2020-09-17 04:46 UTC, alrz1999 commented on Projects/Phase12-Apm/Phase12-Apm.md
> +        ها لایبرری های
fixed

2020-09-17 04:46 UTC, alrz1999 commented on Projects/Phase12-Apm/Phase12-Apm.md
> +        این بخش وظیفه‍ی دریافت اطلاعات از
fixed

2020-09-17 06:38 UTC, mhaghighat20 approved these changes

2020-09-18 17:59 UTC, merged