Bijan/frontend init
Star-Academy/codestar-internship pull request #87
Opened 2021-07-18 00:29 UTC by BijanEisapour

2021-07-18 06:28 UTC, mhaghighat20 requested changes
مرسی بیژن جان، من 3 تا نکته نوشتم که به نظرم نامگذاری فایل ها و هماهنگی با پروژه مهندسی نرم افزار نکات مهمی هستن.
@BijanEisapour @mahdimalverdi

2021-07-18 06:28 UTC, mhaghighat20 commented on Projects/Summer1400/FrontendPlan.md
> +- An app like spotify where user can signup/login and make a collection/playlist of their favorite musics
اگر پروژه اصلی اسپاتیفای باشه نمی تونن در نهایت پروژه شون رو وصل کنن به پروژه تیم مهندسی نرم افزار

2021-07-18 06:28 UTC, mhaghighat20 commented on Projects/Summer1400/FrontendPlan.md
> +-  [Phase01-HTML](../Frontend/Phase01-HTML/Phase01-HTML.md)
پیشنهاد من اینه که توی همه اسم ها به جای
Phase01
بنویسیم
FrontEndPhase01
که با فاز های مهندسی نرم افزار اشتباه نشه

2021-07-18 06:28 UTC, mhaghighat20 commented on Demos/Frontend/pages/Phase01-HTML/index.html
> +<!DOCTYPE html>
نظرتون در مورد این که
github pages
رو روی این کانفیگ کنیم که از طریق
github.io
بتونن صفحه html 
رو توی مرورگر ببینن چیه؟

2021-07-18 07:04 UTC, BijanEisapour commented on Projects/Summer1400/FrontendPlan.md
> +- An app like spotify where user can signup/login and make a collection/playlist of their favorite musics
چرا مگه مشکلی داره؟

2021-07-18 07:05 UTC, BijanEisapour commented on Projects/Summer1400/FrontendPlan.md
> +-  [Phase01-HTML](../Frontend/Phase01-HTML/Phase01-HTML.md)
من فازهای فرانت رو گذاشت تو پوشۀ جداگانه که شلوغ نشه ولی میتونم بذارمشون در کنار همون فازهای قبلی و اسمشون رو اینجوری که نوشتی بذارم 
کدوم رو انجام بدم؟

2021-07-18 07:05 UTC, BijanEisapour commented on Demos/Frontend/pages/Phase01-HTML/index.html
> +<!DOCTYPE html>
همین کارو انجام دادم 
الان رو لینک‌های فاز 1 اگه بزنی میاره اونا رو

2021-07-18 08:10 UTC, mhaghighat20 commented on Projects/Summer1400/FrontendPlan.md
> +-  [Phase01-HTML](../Frontend/Phase01-HTML/Phase01-HTML.md)
وویس فرستادم :)

2021-07-18 08:10 UTC, mhaghighat20 commented on Demos/Frontend/pages/Phase01-HTML/index.html
> +<!DOCTYPE html>
به به

2021-07-18 08:10 UTC, mhaghighat20 commented on Projects/Summer1400/FrontendPlan.md
> +- An app like spotify where user can signup/login and make a collection/playlist of their favorite musics
وویس دادم :)

2021-07-21 14:58 UTC, mhaghighat20 approved these changes

2021-07-22 05:30 UTC, mahdimalverdi approved these changes

2021-07-22 05:30 UTC, mhaghighat20 commented
Closes #81

2021-07-22 12:09 UTC, merged

2021-07-22 13:30 UTC, mhaghighat20 commented
fixed #81